### ISSUE TITLE
Install error "No matching distribution found for torchrl>=0.2.0"

### ISSUE THREAD

**Issue by tmorstyn** [facebookresearch/BenchMARL#29]
Hi, I am receiving the following error when trying to install: "ERROR: Could not find a version that satisfies the requirement torchrl>=0.2.0 (from benchmarl) (from versions: 0.0.1a0, 0.0.1b0, 0.0.1rc0, 0.0.2a0, 0.0.3, 0.0.4a0, 0.0.4b0, 0.0.4, 0.0.5, 0.1.0, 0.1.1)
ERROR: No matching distribution found for torchrl>=0.2.0"

**Comment by matteobettini** [comment]
Hello, thanks for posting your issue. Could you provide some info about your system (OS 
, python version)?

cc @vmoens

**Comment by tmorstyn** [comment]
macOS 13.4.1, Python 3.7.16

**Comment by matteobettini** [comment]
My guess is that this is caused by the fact that torchrl dropped support for python 3.7 and thus there are no wheels published for it.
See the first lines of https://github.com/pytorch/rl/releases/tag/v0.2.0
To see if this is the case I would try with python>=3.8 and see if the issue persits.

If it was indeed python 3.7 and for some reason you strongly need that version, I can suggest opening an issue in the torchrl repo.


Some related issues that might be helpful:
https://github.com/pytorch/rl/issues/1312
https://github.com/pytorch/rl/issues/736

**Comment by vmoens** [comment]
Same for PyTorch in general. TorchRL follows PyTorch closely regarding python compatibility
